### ISSUE TITLE
GUI, displaying problem

### ISSUE THREAD

**Issue by Hayder19** [eroots/gams#6]
Dear Eric,
Thank you for making this valuable code available!
I have updated the GAMS code, but unfortunately, the following issue still exists. 
The bottom part of the GUI of the GAMS is out of my screen display, and I tried to adjust it from the display setting, but I could not fix it.
![GUI_Display issue](https://user-images.githubusercontent.com/78302489/211641627-c3ab0173-1798-4307-bc7a-a2caded4d5c9.jpg). This image shows that some of the grids in the bottom can not be reached (tick).

**Comment by eroots** [comment]
Hi Hayder,
Thanks for brining this to my attention.
Did you update the code from the dev branch? I've refactored the left-side dock so that it doesn't take up as much space vertically, which should make it more accessible on most screens.
It should now look like this:
![image](https://user-images.githubusercontent.com/25284319/211647867-d37f67e3-4905-4890-b3b2-f48d9c05a081.png)

**Comment by Hayder19** [comment]
Thank you E
![SD_RTPVD_OK](https://user-images.githubusercontent.com/78302489/211663863-97a00371-045e-4871-9c7e-bd3cf17a2c5e.png)
ric!
